accountapp/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from accountapp.views import AccountCreateView, AccountDeleteView, \
    AccountUpdateView, AccountDetailView

from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LoginView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

blog_prj/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mvtapps/', include('mvtapp.urls')),
    path('accounts/', include('accountapp.urls')),
]

mvtapp/urls.py
from django.urls import path
from mvtapp.views import detail

app_name = 'mvtapp'

urlpatterns = [
    path('detail/', detail, name='detail'),
]

accountapp/models.py
from django.db import models

# Create your models here.

mvtapp/models.py
from django.db import models

# Create your models here.

class LectureDetail(models.Model):
    title = models.CharField(max_length=255, null=False)
    count = models.IntegerField(null=False)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

accountapp/views.py
from django.shortcuts import render
from django.views import generic

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import generic

# Create your views here.
class AccountCreateView(generic.CreateView):
    #pass
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy("mvtapp:detail")
    template_name = 'accountapp/create.html'
    context_object_name = 'objUser'

class AccountDetailView(generic.DetailView):
    model = User
    template_name = 'accountapp/detail.html'
    context_object_name = 'objUser'

class AccountUpdateView(generic.UpdateView):
    model = User
    form_class = AccountUpdateForm
    success_url = reverse_lazy("mvtapp:detail")
    template_name = 'accountapp/update.html'
    context_object_name = 'objUser'

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated and self.get_object() == self.request.user:
            return super().get(*args, **kwargs)
        else:
            #return HttpResponseRedirect(reverse('accountapp:login'))
            return HttpResponseForbidden()

    def post(self, *args, **kwargs):
        if self.request.user.is_authenticated and self.get_object() == self.request.user:
            return super().post(*args, **kwargs)
        else:
            #return HttpResponseRedirect(reverse('account:login'))
            return HttpResponseForbidden()

class UpdateView(SingleObjectTemplateResponseMixin, BaseUpdateView):
    """View for updating an object, with a response rendered by a template."""
    template_name_suffix = '_form'

class BaseUpdateView(ModelFormMixin, ProcessFormView):
    """
    Base view for updating an existing object.

    Using this base class requires subclassing to provide a response mixin.
    """
    def get(self, *args, **kwargs):
        self.object = self.get_object()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)


class AccountDeleteView(generic.DetailView):
    model = User
    success_url = reverse_lazy("accountapp:login")
    template_name = 'accountapp/delete.html'
    context_object_name = 'objUser'

mvtapp/views.py
from django.http import HttpResponse
from django.shortcuts import render

from django.http import HttpResponse

# Create your views here.

from mvtapp.models import LectureDetail

from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from mvtapp.models import LectureDetail
from django.urls import reverse

def detail(request):

        if request.user.is_authenticated:
                if request.method == 'POST':
                        title = request.POST.get('title')
                        count = request.POST.get('count')

                        # ORM을 위한, 모델 오브젝트 생성
                        data = LectureDetail()
                        data.title = title
                        data.count = int(count)

                        data.save()

                        return HttpResponseRedirect(reverse('mvtapp:detail'))
                        #after input, for review datas in DB
                        #datas = LectureDetail.objects.all()

                        #return render(request, 'mvtapp/new_mvt_detail.html', context={'datas':datas})
                else:
                    datas = LectureDetail.objects.all()

                return render(request, 'mvtapp/new_mvt_detail.html', context={'datas':datas})

        else:
            return HttpResponseRedirect(reverse('accountapp:login'))
        #return HttpResponse('response detail')
        #return render(request, 'mvtapp/new_mvt_detail.html')

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align:center; width:20rem; margin: 2rem auto;">
        <h3> Registration </h3>

        <div>
            <form action="{% url 'accountapp:create'%}" method="post">
                {% csrf_token %}

                {% bootstrap_form form %}
                <div>
                    <input type="submit" class="btn btn-primary mt-3">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% block content %}

    <div style="text-align:center; width:20rem; margin: 2rem auto;">
        <h3> Delete Account </h3>

        <div>
            <form action="{% url 'accountapp:delete' pk=objUser.pk %}" method="post">
                {% csrf_token %}

                <div>
                    <input type="submit" class="btn btn-primary mt-3">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}
    <div style="text-align:center;">
        <h4> User Info(Detail) </h4>

        <div>
            <p> username : {{ objUser.username }}</p>
            <p> date_joined : {{ objUser.date_joined }} </p>
        </div>

        {% if objUser == user %}
            <div>
                <a href="{% url 'accountapp:update' pk=user.pk %}">Edit Account</a>
            </div>

            <div>
                <a href="{% url 'accountapp:delete' pk=user.pk %}">Delete Account</a>
            </div>
        {% endif %}
    </div>
{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align:center; width:20rem; margin: 2rem auto;">
        <h3> Login View </h3>
        <div>
            <form action="" method="post">
                {% csrf_token %}

                {% bootstrap_form form %}
                <input type="submit" class="btn btn-primary mt-3">
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align:center; width:20rem; margin: 2rem auto;">
        <h3> Account Update </h3>

        <div>
            <form action="{% url 'accountapp:update' pk=user.pk %}" method="post">
                {% csrf_token %}

                {% bootstrap_form form %}
                <div>
                    <input type="submit" class="btn btn-primary mt-3">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

mvtapp/templates/mvtapp/mvt_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>mvt_detail</title>
</head>
<body>
    <div>
      <div>
        <span>NAV1</span>
        <span>NAV2</span>
        <span>NAV3</span>
      </div>
    </div>

    <div>
        <p>가변영역(콘텐츠가 담길것입니다!!!)</p>
    </div>

    <div>
        <span>도서관</span>
        <span>정보통신처</span>
        <span>발전기금</span>
        <span>연구통합검색</span>
        <span>규정관리</span>
    </div>
</body>
</html>

mvtapp/templates/mvtapp/mvt_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MVT_TEST</title>
</head>
<body>
    <h1>mvt_test page!!!</h1>
</body>
</html>

mvtapp/templates/mvtapp/new_mvt_detail.html
{% extends 'base.html' %}

{% block content %}
  <div style="text-align : center">
      <h2>Input Data</h2>

      <form action="/mvtapps/detail/" method="post">
          {% csrf_token %}
          <div>
              <input type="text" name="title" placeholder="과목명을 넣어주세요">
          </div>

          <div style="margin: 1rem">
              <input type="text" name="count" placeholder="수강인원을 넣어주세요">
          </div>

          <div style="margin: 1rem">
              <input type="submit" class="btn btn-primary">
          </div>
      </form>

      <hr>
      <div style="overflow:scroll; height: 30rem; text-align:center;">
      {% if datas %}
          {% for data in datas %}
              <h5> Title : {{ data.title }}, Count : {{ data.count }}</h5>
          {% endfor %}
      {% endif %}
      </div>

  </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}

<body>
    {% include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}

    <hr>

    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
    <div class="footer">
        <span>도서관</span>
        <span>정보통신처</span>
        <span>발전기금</span>
        <span>연구통합검색</span>
        <span>규정관리</span>
    </div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>mvt_detail</title>

    <!-- style sheet link -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</head>

templates/header.html
<div class="header">
    <div><h1>KOOKMIN</h1></div>
        <div>
            <span>NAV1</span>
            <span>NAV2</span>
            <span>NAV3</span>

            {%  if not user.is_authenticated %}
                <a href="{% url 'accountapp:login' %}">
                    <span>login</span>
                </a>

                <a href="{% url 'accountapp:create' %}">
                    <span>Registration</span>
                </a>

            {% else %}  <!-- user가 로그인 상태 -->

                <a href="{% url 'accountapp:detail' pk=user.pk %}">
                    <span>userinfo</span>
                </a>

                <a href="{% url 'accountapp:logout' %}">
                    <span>logout</span>
                </a>
            {% endif %}
        </div>
</div>